backfill_statistics:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: netz_noe_smartmeter
    start_year:
      required: false
      example: 2023
      selector:
        number:
          min: 2000
          max: 2030
          mode: box
